name: Push Updated Categorized Links

on:
  repository_dispatch:
    types: [update_categorized_links]

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Idol-Categorizer repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Write updated idol_gallery_links.txt
        run: |
          echo "${{ github.event.client_payload.updated_file }}" > idol_gallery_links.txt

      - name: Commit and push changes
        run: |
          git config user.name "Idol-Categorizer Bot"
          git config user.email "bot@users.noreply.github.com"
          git add idol_gallery_links.txt
          git commit -m "Auto-update categorized idols" || echo "No changes to commit"
          git push
