name: Receive Categorizer Update Request

on:
  repository_dispatch:
    types: [commit_categorized_updates]

jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - name: Forward categorized file to Push workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "🚀 Forwarding categorized update to push-updated-links.yml"
          echo "${{ github.event.client_payload.updated_file }}" | base64 --decode > idol_gallery_links.txt

          gh api repos/beltedblinds/Idol-Categorizer/dispatches \
            -f event_type=update_links \
            -f client_payload="$(jq -n --arg updated_file "${{ github.event.client_payload.updated_file }}" '{updated_file:$updated_file}')" \
            -H "Authorization: token $GH_TOKEN"
