name: Push Updated Idol List

on:
  repository_dispatch:
    types: [commit_categorized_updates]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout idols-media-01 repo
        uses: actions/checkout@v4
        with:
          repository: beltedblinds/idols-media-01
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Update idol_gallery_links.txt
        run: |
          echo "${{ github.event.client_payload.updated_file }}" > idol_gallery_links.txt
          git config user.name "Idol-Categorizer Bot"
          git config user.email "bot@users.noreply.github.com"
          git add idol_gallery_links.txt
          git commit -m "Auto-update categorized idols" || echo "No changes"
          git push
