name: Save Categorized File

on:
  repository_dispatch:
    types: [save_categorized]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Save updated idol_gallery_links.txt
        run: |
          echo "${{ github.event.client_payload.updated_file }}" > idol_gallery_links.txt
          git config user.name "Idol-Categorizer Bot"
          git config user.email "bot@users.noreply.github.com"
          git add idol_gallery_links.txt
          git commit -m "Save categorized idols" || echo "No changes to commit"
          git push
