name: Receive Categorizer Update Request

on:
  repository_dispatch:
    types: [commit_categorized_updates]

jobs:
  forward:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Forward categorized update to idols-media-01
        run: |
          echo "Forwarding categorized update to idols-media-01…"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/beltedblinds/idols-media-01/dispatches \
            -d '{"event_type":"commit_categorized_updates","client_payload":{"updated_file":"'"$(cat idol_gallery_links.txt | jq -Rs .)"'"}}'
