name: Save Categorized File

on:
  repository_dispatch:
    types: [save_categorized]

jobs:
  save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Save categorized data
        run: |
          echo "${{ github.event.client_payload.updated_file }}" > idol_gallery_links.txt
          git config user.name "Idol-Categorizer Bot"
          git config user.email "bot@users.noreply.github.com"
          git add idol_gallery_links.txt
          git commit -m "Save categorized idols" || echo "No changes"
          git push
