name: GH_TOKEN Diagnostic

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print confirmation
        run: |
          echo "✅ Workflow triggered successfully with GH_TOKEN!"
